import { DEFAULT_REFRESHER_PCT_OF_BASE, EMPLOYEE_401K_LIMIT_2026, MODEL } from "./model";
import type { ProjectionScenario, ScenarioDefinition } from "./types";

export const DEFAULT_SCENARIO: ProjectionScenario = {
  compensation: {
    baseSalary: 129000,
    initialRsuGrantValue: 140000,
    monthsAtAmazon: 24,
    futureAnnualRefreshGrantValue: Math.round(129000 * DEFAULT_REFRESHER_PCT_OF_BASE),
    annualRaisePct: 3,
    useSalaryGrowthForRefreshers: true,
  },
  balances: {
    currentNetWorth: 50000,
    current401kBalance: 10000,
    currentAmazonStockBalance: 0,
    studentLoanBalance: 60000,
  },
  strategy: {
    extraInvestmentPct: 15,
    k401ContributionPct: 4,
    employerMatchPct: 50,
    employerMatchLimitPct: 4,
    payStudentLoanBeforeInvesting: true,
  },
  market: {
    fundAnnualReturnPct: 5,
    amazonStockAnnualReturnPct: 5,
    studentLoanInterestRatePct: 13,
  },
  expenses: {
    monthlyRent: 2578,
    monthlyParking: 275,
    monthlyHealthDentalBenefits: 500,
    otherMonthlyFixedExpenses: 0,
  },
  projection: {
    maxYears: 50,
  },
  overrides: {
    firstMonth: {
      useActualPaycheck: true,
      regularGross: 9283.83,
      signingBonus: 50100,
      takeHome: 41330.61,
      employee401k: 0,
      employer401k: 0,
      useActualContributionAllocation: false,
      studentLoanPayment: 0,
      taxableFundContribution: 0,
    },
  },
};

export const DEFAULT_SCENARIO_DEFINITION: ScenarioDefinition = {
  version: 2,
  name: "Default scenario",
  horizonMonths: 600,
  targetNetWorth: MODEL.targetNetWorth,
  accounts: [
    { id: "cash", label: "Cash", kind: "cash", openingBalance: 0, annualRate: 0, minBalance: 0 },
    { id: "k401", label: MODEL.accounts.k401.label, kind: "asset", openingBalance: 10000, annualRate: 0.05, color: MODEL.accounts.k401.color, minBalance: 0 },
    { id: "taxableFund", label: MODEL.accounts.taxableFund.label, kind: "asset", openingBalance: 40000, annualRate: 0.05, color: MODEL.accounts.taxableFund.color, minBalance: 0 },
    { id: "amazonStock", label: MODEL.accounts.amazonStock.label, kind: "asset", openingBalance: 0, annualRate: 0.05, color: MODEL.accounts.amazonStock.color, minBalance: 0 },
    { id: "studentLoan", label: MODEL.accounts.studentLoan.label, kind: "liability", openingBalance: 60000, annualRate: 0.13, color: MODEL.accounts.studentLoan.color, minBalance: 0 },
  ],
  modules: [
    {
      id: "employment",
      type: "employmentIncome",
      annualBaseSalary: 129000,
      annualRaiseRate: 0.03,
      firstMonthActualPaycheck: {
        enabled: true,
        regularGross: 9283.83,
        signingBonus: 50100,
        takeHome: 41330.61,
      },
    },
    {
      id: "retirement-plan",
      type: "retirementPlan",
      destinationAccountId: "k401",
      annualEmployeeLimit: EMPLOYEE_401K_LIMIT_2026,
      employeeContributionRate: 0.04,
      employerMatchRate: 0.5,
      employerMatchLimitRate: 0.04,
      firstMonthOverride: {
        enabled: true,
        employeeContribution: 0,
        employerContribution: 0,
      },
    },
    {
      id: "rent",
      type: "recurringFlow",
      label: "Rent",
      amount: 2578,
      startMonth: 0,
      endMonth: null,
      eventType: "expense",
      source: "rent",
      taxTreatment: "after-tax",
    },
    {
      id: "parking",
      type: "recurringFlow",
      label: "Parking",
      amount: 275,
      startMonth: 0,
      endMonth: null,
      eventType: "expense",
      source: "parking",
      taxTreatment: "after-tax",
    },
    {
      id: "health-dental-benefits",
      type: "recurringFlow",
      label: "Health/dental benefits",
      amount: 500,
      startMonth: 0,
      endMonth: null,
      eventType: "expense",
      source: "health-dental-benefits",
      taxTreatment: "after-tax",
      skipWhenActualFirstMonthPaycheck: true,
    },
    {
      id: "other-fixed-expenses",
      type: "recurringFlow",
      label: "Other fixed expenses",
      amount: 0,
      startMonth: 0,
      endMonth: null,
      eventType: "expense",
      source: "other-fixed-expenses",
      taxTreatment: "after-tax",
    },
    {
      id: "equity-grants",
      type: "equityGrantSeries",
      destinationAccountId: "amazonStock",
      employeeMonthsAtProjectionStart: 24,
      initialGrantValue: 140000,
      refreshGrantValue: Math.round(129000 * DEFAULT_REFRESHER_PCT_OF_BASE),
      firstRefreshGrantMonth: 36,
      refreshFrequencyMonths: 12,
      useSalaryGrowthForRefreshers: true,
      annualRaiseRate: 0.03,
      annualBaseSalary: 129000,
      salaryLinkedRefreshPctOfBase: DEFAULT_REFRESHER_PCT_OF_BASE,
      vestingSchedule: MODEL.rsuPlans.amazonInitial.events.map((event) => ({
        monthOffset: event.month,
        pct: event.pct,
      })),
    },
    {
      id: "taxes",
      type: "tax",
    },
  ],
  allocationPolicies: [
    {
      id: "after-tax-allocation",
      sourceAccountId: "cash",
      rateOfAvailable: 0.15,
      sweepRemainderFromSource: true,
      steps: [
        { destinationAccountId: "studentLoan", destinationDeltaSign: -1, mode: "reduceToZero" },
        { destinationAccountId: "taxableFund", destinationDeltaSign: 1, mode: "allRemaining" },
      ],
      overrides: [],
    },
  ],
};
