import { ArrowRight, Info, Pencil, TriangleAlert } from 'lucide-react';
import type { Plan } from '../domain/model.ts';
import { currentNetWorth, type Projection, type RangeResult } from '../domain/projection.ts';
import { dateLabel, money, percent, shiftDate } from '../domain/format.ts';
import { Badge, Modal } from './ui.tsx';
import type { EditorTarget } from './PlanEditor.tsx';
import { AccountDialog } from './AccountDialog.tsx';

export type EvidenceTarget = { kind: 'position' } | { kind: 'account'; id: string } | { kind: 'failure' } | { kind: 'goal'; id: string } | { kind: 'timing' } | { kind: 'method' };

export function EvidenceDialog({ target, plan, projection, range, temporary = false, serverMode = false, onClose, onEdit }: { target: EvidenceTarget; plan: Plan; projection: Projection; range: RangeResult | null; temporary?: boolean; serverMode?: boolean; onClose: () => void; onEdit: (target: EditorTarget) => void }) {
  const edit = (target: EditorTarget) => { onClose(); onEdit(target); };
  if (target.kind === 'position') return <Modal title="The basis of your net worth" eyebrow="Current position" onClose={onClose}><div className="evidence-amount">{money(currentNetWorth({ projection, plan }))}</div><p className="muted">Assets minus debts · starting {dateLabel(plan.startDate, true)}</p><dl className="detail-list">{plan.accounts.filter((account) => account.enabled).map((account) => <div key={account.id}><dt>{account.name}<small>{account.provenance} · {dateLabel(account.observedOn, true)}</small></dt><dd>{money(account.balance)}</dd></div>)}</dl><div className="inline-notice"><Info size={18} /><span>{plan.origin === 'example' ? 'All balances are illustrative example data. ' : ''}Starting values mix balance checks and estimates. Older checks are carried forward without reconstructing missing history.</span></div></Modal>;
  if (target.kind === 'account') {
    const account = plan.accounts.find((a) => a.id === target.id);
    if (!account) return null;
    return <AccountDialog account={account} plan={plan} projection={projection} temporary={temporary} onClose={onClose} onEdit={edit} />;
  }
  if (target.kind === 'failure') {
    const failure = projection.firstFailure;
    if (!failure) return <Modal title="All movements funded" onClose={onClose}><p>No underfunded movements occur in this base-case horizon.</p></Modal>;
    const movement = plan.movements.find((m) => m.id === failure.movementId);
    const account = plan.accounts.find((a) => a.id === failure.fromId);
    const destination = plan.accounts.find((a) => a.id === failure.toId);
    const bindingTypes = failure.constraintTypes ?? [];
    const sourceFloorBinding = bindingTypes.includes('source-floor') || failure.constraint === 'Protected account balance';
    const destinationCeilingBinding = bindingTypes.includes('destination-ceiling') || failure.constraint === 'Destination account ceiling';
    return <Modal title={failure.name} eyebrow="First underfunded movement" onClose={onClose}><div className="evidence-date"><TriangleAlert size={18} />{dateLabel(failure.date, true)} · modeled outcome</div><div className="failure-comparison"><div><span>Requested</span><strong>{money(failure.requested)}</strong></div><ArrowRight size={19} /><div><span>Realized</span><strong>{money(failure.realized)}</strong></div></div><dl className="detail-list"><div><dt>Shortfall</dt><dd>{money(failure.requested - failure.realized)}</dd></div><div><dt>Funding account</dt><dd>{account?.name ?? 'External income'}</dd></div><div><dt>Funding evidence</dt><dd>{failure.available === null ? (failure.constraint ?? 'Funded amount unavailable') : failure.available === Infinity ? 'External funding' : typeof failure.available === 'number' && Number.isFinite(failure.available) ? money(failure.available) : 'Funded amount unavailable'}</dd></div><div><dt>Binding constraint</dt><dd>{failure.constraint}</dd></div>{sourceFloorBinding && <div><dt>Protected balance</dt><dd>{money(account?.floor ?? 0)}</dd></div>}{destinationCeilingBinding && <div><dt>Destination ceiling</dt><dd>{money(destination?.ceiling ?? 0)}</dd></div>}{!sourceFloorBinding && !destinationCeilingBinding && <div><dt>Binding constraint</dt><dd>{failure.constraint}</dd></div>}</dl><div className="inline-notice amber"><Info size={19} /><span>The unpaid amount is not automatically borrowed or rescheduled. Later balances include only the realized movement, so the projected destination does not mean the whole plan is affordable.</span></div><p className="section-note">Inspect the amount, date, funding account, or protected balance. The 30-day cash view is a separate timing check.</p>{movement && <div className="modal-actions"><button className="button primary" onClick={() => edit({ kind: 'movement', item: movement })}>Try changing this expense <ArrowRight size={16} /></button></div>}</Modal>;
  }
  if (target.kind === 'goal') {
    const result = projection.goals.find((g) => g.goal.id === target.id);
    if (!result) return null;
    return <Modal title={result.goal.name} eyebrow="Goal evidence" onClose={onClose}><div className="evidence-amount">{result.firstDate ? result.current >= result.goal.target ? 'Already reached' : dateLabel(result.firstDate) : 'Beyond this horizon'}</div><p className="muted">First reached in the base case</p><dl className="detail-list"><div><dt>Measure</dt><dd>{result.goal.kind === 'net-worth' ? 'Household net worth' : plan.accounts.find((a) => a.id === result.goal.accountId)?.name}</dd></div><div><dt>Target</dt><dd>{money(result.goal.target)}</dd></div><div><dt>At the start</dt><dd>{money(result.current)}</dd></div><div><dt>At the horizon</dt><dd>{money(result.final)}</dd></div><div><dt>Still met at horizon</dt><dd>{result.final >= result.goal.target ? 'Yes' : 'No'}</dd></div>{range && <div><dt>Scenarios reaching the target</dt><dd>{percent(range.goalSuccess[result.goal.id] ?? 0)} of {range.count}</dd></div>}</dl><p className="section-note">The first crossing of a threshold is a milestone. It does not establish sustained spending coverage, retirement readiness, or future certainty.</p><div className="modal-actions"><button className="button primary" onClick={() => edit({ kind: 'goal', item: result.goal })}><Pencil size={16} />Edit goal</button></div></Modal>;
  }
  if (target.kind === 'timing') {
    const end = shiftDate({ date: plan.startDate, days: 30 });
    const events = projection.movements.filter((m) => m.date <= end);
    return <Modal title="The next 30 days" eyebrow={`${dateLabel(plan.startDate, true)} to ${dateLabel(end, true)}`} onClose={onClose} wide><p className="form-intro">Planned cash timing from the same starting balances. These amounts are scheduled, not bank-confirmed.</p><div className="table-scroll"><table><thead><tr><th scope="col">Date</th><th scope="col">Movement</th><th scope="col">Requested</th><th scope="col">Funded</th></tr></thead><tbody>{events.map((event, index) => <tr key={`${event.movementId}-${index}`}><td>{dateLabel(event.date, true)}</td><th scope="row">{event.name}</th><td>{money(event.requested)}</td><td>{money(event.realized)}{event.constraint && <Badge tone="amber">Shortfall</Badge>}</td></tr>)}</tbody></table></div>{!events.length && <p>No movements scheduled in this period.</p>}<div className="inline-notice"><Info size={18} /><span>Cash above protected balances is not a safe-to-spend recommendation. Account timing, future commitments and unmodeled expenses can still limit spending.</span></div></Modal>;
  }
  return <Modal title="A considered view of your future" eyebrow="How Waypoint works" onClose={onClose}><div className="method-steps"><div><span>01</span><div><h3>Start with what you know</h3><p>Recorded balances and clearly marked estimates establish today’s position.</p></div></div><div><span>02</span><div><h3>Follow the plan forward</h3><p>Dated income, spending, transfers and account rates produce a base case. Optional ranges vary investment returns across 400 scenarios.</p></div></div><div><span>03</span><div><h3>Try a change, then decide</h3><p>Edit a temporary version, compare the outcome, and explicitly save or discard. Drafts stay in this browser between visits.</p></div></div></div><div className="inline-notice"><Info size={18} /><span>{serverMode ? 'The saved financial model is loaded from the Waypoint server. Temporary edits stay in this browser until you explicitly save them. Projections are planning aids and do not provide investment, tax or legal advice.' : 'This independent frontend uses a local financial model. No bank or server is connected. Projections are planning aids and do not provide investment, tax or legal advice.'}</span></div></Modal>;
}
