import type { Plan } from "../domain/model.ts";

// A small household used only by unit tests. Production code has no
// sample plan: every projection comes from the Go engine.
export const testPlan: Plan = {
	schemaVersion: 1,
	name: "Our household",
	origin: "example",
	startDate: "2026-09-24",
	updatedAt: "2026-09-24T09:00:00.000Z",
	revision: 1,
	readOnly: false,
	accounts: [
		{
			id: "checking",
			name: "Everyday checking",
			kind: "cash",
			enabled: true,
			balance: 18250,
			floor: 2500,
			ceiling: null,
			observedOn: "2026-09-24",
			provenance: "recorded",
			source: "Example balance check",
			readOnly: false,
		},
		{
			id: "savings",
			name: "Emergency fund",
			kind: "cash",
			enabled: true,
			balance: 42000,
			floor: 0,
			ceiling: null,
			observedOn: "2026-09-24",
			provenance: "recorded",
			source: "Example balance check",
			readOnly: false,
		},
		{
			id: "brokerage",
			name: "Investment portfolio",
			kind: "investment",
			enabled: true,
			balance: 214800,
			floor: 0,
			ceiling: null,
			observedOn: "2026-09-24",
			provenance: "recorded",
			source: "Example balance check",
			readOnly: false,
		},
		{
			id: "retirement",
			name: "Retirement savings",
			kind: "investment",
			enabled: true,
			balance: 326000,
			floor: 0,
			ceiling: null,
			observedOn: "2026-09-24",
			provenance: "recorded",
			source: "Example balance check",
			readOnly: false,
		},
		{
			id: "home",
			name: "Home value",
			kind: "property",
			enabled: true,
			balance: 480000,
			floor: 0,
			ceiling: null,
			observedOn: "2026-09-01",
			provenance: "modeled",
			source: "Example home estimate",
			readOnly: false,
		},
		{
			id: "mortgage",
			name: "Home mortgage",
			kind: "debt",
			enabled: true,
			balance: -278600,
			floor: 0,
			ceiling: 0,
			observedOn: "2026-09-24",
			provenance: "recorded",
			source: "Example balance check",
			readOnly: false,
		},
	],
	movements: [
		{
			id: "pay",
			name: "Household take-home pay",
			amount: 11200,
			amountKnown: true,
			fromId: null,
			toId: "checking",
			frequency: "monthly",
			startDate: "2026-09-28",
			endDate: null,
			annualIncrease: 2.5,
			enabled: true,
			provenance: "planned",
			readOnly: false,
		},
		{
			id: "living",
			name: "Everyday living",
			amount: 5400,
			amountKnown: true,
			fromId: "checking",
			toId: null,
			frequency: "monthly",
			startDate: "2026-10-01",
			endDate: null,
			annualIncrease: 2.5,
			enabled: true,
			provenance: "planned",
			readOnly: false,
		},
		{
			id: "mortgage-payment",
			name: "Mortgage payment",
			amount: 2050,
			amountKnown: true,
			fromId: "checking",
			toId: "mortgage",
			frequency: "monthly",
			startDate: "2026-10-01",
			endDate: null,
			annualIncrease: 0,
			enabled: true,
			provenance: "planned",
			readOnly: false,
		},
		{
			id: "invest",
			name: "Monthly investing",
			amount: 1800,
			amountKnown: true,
			fromId: "checking",
			toId: "brokerage",
			frequency: "monthly",
			startDate: "2026-10-03",
			endDate: null,
			annualIncrease: 2.5,
			enabled: true,
			provenance: "planned",
			readOnly: false,
		},
		{
			id: "retirement-contribution",
			name: "Retirement contribution",
			amount: 1100,
			amountKnown: true,
			fromId: "checking",
			toId: "retirement",
			frequency: "monthly",
			startDate: "2026-10-05",
			endDate: null,
			annualIncrease: 2.5,
			enabled: true,
			provenance: "planned",
			readOnly: false,
		},
		{
			id: "renovation",
			name: "Home renovation",
			amount: 48000,
			amountKnown: true,
			fromId: "checking",
			toId: null,
			frequency: "once",
			startDate: "2028-06-15",
			endDate: null,
			annualIncrease: 0,
			enabled: true,
			provenance: "planned",
			readOnly: false,
		},
		...["2026-06-28", "2026-07-28", "2026-08-28"].map((startDate, index) => ({
			id: `pay-record-${index}`,
			name: "Household payroll",
			amount: 11200,
			amountKnown: true,
			fromId: null,
			toId: "checking",
			frequency: "once" as const,
			startDate,
			endDate: null,
			annualIncrease: 0,
			enabled: true,
			provenance: "recorded" as const,
			readOnly: false,
		})),
	],
	goals: [
		{
			id: "million",
			name: "Build a $1.5M net worth",
			kind: "net-worth",
			target: 1500000,
			accountId: null,
			enabled: true,
		},
		{
			id: "cash-buffer",
			name: "Keep a six-month cushion",
			kind: "reserve",
			target: 32400,
			accountId: "savings",
			enabled: true,
		},
	],
	assumptions: { inflation: 2.5, volatility: 12 },
};
